model:
  task: classification
  name: resnet18
  checkpoint:
    use_pretrained: False
    load_head: False
    path: ~
    optimizer_path: ~
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone:
      name: resnet
      params:
        block_type: basicblock
        norm_type: batch_norm
      stage_params:
        - 
          channels: 64
          num_blocks: 2
        - 
          channels: 128
          num_blocks: 2
          replace_stride_with_dilation: False
        - 
          channels: 256
          num_blocks: 2
          replace_stride_with_dilation: False
        - 
          channels: 512
          num_blocks: 2
          replace_stride_with_dilation: False
    head:
      name: fc
      params:
        num_layers: 1
        intermediate_channels: ~
        act_type: ~
        dropout_prob: 0.
  postprocessor: 
    params: 
      topk_max: 20 
  losses:
    - criterion: cross_entropy
      label_smoothing: 0.
      weight: ~