augmentation:
  img_size: &img_size ~
  recipe:
    - 
      name: RandomResizedCrop
      size: ~
      interpolation: bilinear
    -
      name: RandomHorizontalFlip
      p: ~
    -
      name: RandomVerticalFlip
      p: ~
    -
      name: ColorJitter
      brightness: ~
      contrast: ~
      saturation: ~
      hue: ~
      p: ~
    -
      name: Resize
      size: ~
    -
      name: Pad
      padding: ~