model:
  task: classification
  checkpoint: ./weights/efficientformer/efficientformer_l1_1000d.pth
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone:
      type: efficientformer
    head:
      type: fc
  losses:
    - criterion: label_smoothing_cross_entropy
      smoothing: 0.1
      weight: ~