model:
  task: detection
  checkpoint: ./weights/efficientformer/efficientformer_l1_1000d.pth
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone:
      name: efficientformer
    head:
      name: efficientformer_detection_head
  losses:
    - criterion: roi_head_loss
      weight: ~
    - criterion: rpn_loss
      weight: ~