model:
  task: segmentation
  checkpoint: ./weights/efficientformer/efficientformer_l1_1000d.pth
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone: efficientformer
    head: all_mlp_decoder
  losses:
    - criterion: cross_entropy
      weight: ~
      ignore_index: 255