model:
  task: segmentation
  name: efficientformer_l1
  checkpoint: ./weights/efficientformer/efficientformer_l1_1000d.safetensors
  fx_model_checkpoint: ~
  resume_optimizer_checkpoint: ~
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone:
      name: efficientformer
      params:
        num_attention_heads: 8
        attention_channels: 256  # attention_hidden_size_splitted * num_attention_heads
        attention_dropout_prob: 0.
        attention_value_expansion_ratio: 4
        ffn_intermediate_ratio: 4
        ffn_dropout_prob: 0.
        ffn_act_type: 'gelu'
        vit_num: 1
      stage_params:
        - 
          num_blocks: 3
          channels: 48
        - 
          num_blocks: 2
          channels: 96
        - 
          num_blocks: 6
          channels: 224
        - 
          num_blocks: 4
          channels: 448
    head:
      name: all_mlp_decoder
      params:
        decoder_hidden_size: 256
        classifier_dropout_prob: 0.
  losses:
    - criterion: cross_entropy
      weight: ~
      ignore_index: 255