model:
  task: detection
  name: efficientformer_l1
  checkpoint: ./weights/efficientformer/efficientformer_l1_1000d.pth
  fx_model_checkpoint: ~
  resume_optimizer_checkpoint: ~
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone:
      name: efficientformer
      params:
        num_attention_heads: 8
        attention_hidden_size: 256  # attention_hidden_size_splitted * num_attention_heads
        attention_dropout_prob: 0.
        attention_ratio: 4
        attention_bias_resolution: 16
        pool_size: 3
        intermediate_ratio: 4
        hidden_dropout_prob: 0.
        hidden_activation_type: 'gelu'
        layer_norm_eps: 1e-5
        drop_path_rate: 0.
        use_layer_scale: True
        layer_scale_init_value: 1e-5
        down_patch_size: 3
        down_stride: 2
        down_pad: 1
        vit_num: 1
      stage_params:
        - 
          num_blocks: 3
          hidden_sizes: 48
          downsamples: True
        - 
          num_blocks: 2
          hidden_sizes: 96
          downsamples: True
        - 
          num_blocks: 6
          hidden_sizes: 224
          downsamples: True
        - 
          num_blocks: 4
          hidden_sizes: 448
          downsamples: True
    neck:
      name: fpn
    head:
      name: faster_rcnn
      params:
        # Anchor parameters
        anchor_sizes: [[64,], [128,], [256,], [512,]]
        aspect_ratios: [0.5, 1.0, 2.0]
        # RPN parameters
        rpn_pre_nms_top_n: 2000
        rpn_post_nms_top_n: 2000
        rpn_nms_thresh: 0.7
        rpn_fg_iou_thresh: 0.7
        rpn_bg_iou_thresh: 0.3
        rpn_batch_size_per_image: 256
        rpn_positive_fraction: 0.5
        rpn_score_thresh: 0.0
        # RoI parameters
        roi_output_size: 7
        roi_sampling_ratio: 2
        roi_representation_size: 1024
        # Box parameters
        box_score_thresh: 0.05
        box_nms_thresh: 0.5
        box_detections_per_img: 100
        box_fg_iou_thresh: 0.5
        box_bg_iou_thresh: 0.5
        box_batch_size_per_image: 512
        box_positive_fraction: 0.25
        bbox_reg_weights: ~
  losses:
    - criterion: roi_head_loss
      weight: ~
    - criterion: rpn_loss
      weight: ~