model:
  task: classification
  checkpoint: ./weights/efficientformer/efficientformer_l1_1000d.pth
  architecture:
    full: ~ # auto
    backbone: efficientformer
    head: fc
  losses:
    - criterion: label_smoothing_cross_entropy
      smoothing: 0.01
      weight: ~