model:
  task: segmentation
  checkpoint: ../../weights/modelsearch-trainer-allinone/backbones/efficientformer/efficientformer_l1_1000d.pth
  architecture:
    full: ~ # auto
    backbone: efficientformer
    head: efficientformer_decode_head
  losses:
    - criterion: cross_entropy
      weight: ~
      ignore_index: 255