model:
  task: detection
  checkpoint: ../../weights/netspresso-trainer/efficientformer/efficientformer_l1_1000d.pth
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone: efficientformer
    head: efficientformer_detection_head
  losses:
    - criterion: roi_head_loss
      weight: ~
    - criterion: rpn_loss
      weight: ~