model:
  task: classification
  architecture:
    full: ~ # auto
    backbone: efficientformer
    head: fc
  losses:
    - criterion: label_smoothing_cross_entropy
      smoothing: 0.01
      weight: ~