model:
  task: classification
  checkpoint: ../../weights/modelsearch-trainer-allinone/backbones/mobilevit/mobilevit_s.pth
  architecture:
    full: ~ # auto
    backbone: mobilevit
    head: fc
  losses:
    - criterion: label_smoothing_cross_entropy
      smoothing: 0.1
      weight: ~