model:
  task: segmentation
  checkpoint: /CHECKPOINT/full/pidnet/pidnet_s.pth
  architecture:
    full: pidnet
    backbone: ~
    head: ~
  losses:
    - criterion: pidnet_cross_entropy
      weight: ~
      ignore_index: 255
    - criterion: boundary_loss
      weight: 20.0
    - criterion: pidnet_cross_entropy_with_boundary
      weight: ~
      ignore_index: 255