model:
  task: classification
  checkpoint: ../../weights/modelsearch-trainer-allinone/backbones/resnet/resnet50.pth
  architecture:
    full: ~ # auto
    backbone: resnet50
    head: fc
  losses:
    - criterion: label_smoothing_cross_entropy
      smoothing: 0.01
      weight: ~