model:
  task: segmentation
  checkpoint: /CHECKPOINT/backbones/segformer/segformer.pth
  architecture:
    full: ~ # auto
    backbone: segformer
    head: segformer_decode_head
  losses:
    - criterion: cross_entropy
      weight: ~
      ignore_index: 255