version: "3.9"

# docker compose run --service-ports --name modelsearch-trainer-allinone-dev modelsearch-trainer-allinone bash

services:
  modelsearch-trainer-allinone:
    image: pytorch/pytorch:1.12.0-cuda11.3-cudnn8-devel
    container_name: modelsearch-trainer-allinone-dev
    ipc: host
    ports:
      - "50004:50002"
    volumes:
      - /ssd1/hksong/modelsearch-trainer-allinone-dev:/workspace
      - /ssd1/hksong/DATA:/DATA
      - /ssd1/hksong/LOG:/LOG
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0', '1', '2', '3', '4', '5', '6', '7' ]
              capabilities: [ gpu ]
