model:
  task: classification
  checkpoint: ./weights/vit/vit-tiny.pth
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone:
      name: vit
    head:
      name: fc
  losses:
    - criterion: label_smoothing_cross_entropy
      smoothing: 0.1
      weight: ~