model:
  task: detection
  checkpoint: ./weights/yolox/yolox_s.pth
  fx_model_checkpoint: ~
  resume_optimizer_checkpoint: ~
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone:
      name: cspdarknet
      dep_mul: 0.33
      wid_mul: 0.5
    head:
      name: yolox_head
  losses:
    - criterion: yolox_loss
      weight: ~