model:
  task: detection
  name: yolox_s
  checkpoint:
    use_pretrained: True
    load_head: False
    path: ~
    fx_model_path: ~
    optimizer_path: ~
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone:
      name: cspdarknet
      params:
        dep_mul: &dep_mul 0.33
        wid_mul: 0.5
        act_type: &act_type "silu"
      stage_params: ~
    neck:
      name: yolopafpn
      params:
        dep_mul: *dep_mul
        act_type: *act_type
    head:
      name: anchor_free_decoupled_head
      params:
        act_type: *act_type
        # postprocessor - decode
        score_thresh: 0.7
        # postprocessor - nms
        nms_thresh: 0.45
        class_agnostic: False
  losses:
    - criterion: yolox_loss
      weight: ~
      l1_activate_epoch: 1