model:
  task: segmentation
  name: resnet50
  checkpoint:
    use_pretrained: True
    load_head: True
    path: ~
    fx_model_path: ~
    optimizer_path: ~
  freeze_backbone: False
  architecture:
    full:
      name: ~ # auto
    backbone:
      name: resnet
      params:
        block_type: bottleneck
        norm_type: batch_norm
        return_stage_idx: ~
        split_stem_conv: False
        first_stage_shortcut_conv: False
      stage_params:
        - 
          channels: 64
          num_blocks: 3
        - 
          channels: 128
          num_blocks: 4
          replace_stride_with_dilation: False
          replace_stride_with_pooling: False
        - 
          channels: 256
          num_blocks: 6
          replace_stride_with_dilation: False
          replace_stride_with_pooling: False
        - 
          channels: 512
          num_blocks: 3
          replace_stride_with_dilation: False
          replace_stride_with_pooling: False
    head:
      name: all_mlp_decoder
      params:
        intermediate_channels: 256
        classifier_dropout_prob: 0.
  postprocessor: ~
  losses:
    - criterion: seg_cross_entropy
      weight: ~
      ignore_index: 255 # Default undefined class is 255