model:
  task: segmentation
  checkpoint: ./weights/resnet/resnet50.pth
  fx_model_checkpoint: ~
  resume_optimizer_checkpoint: ~
  freeze_backbone: False
  architecture:
    full:
      name: ~ # auto
    backbone:
      name: resnet50
      block: bottleneck
      layers: [3, 4, 6, 3]
    head:
      name: all_mlp_decoder
  losses:
    - criterion: cross_entropy
      weight: ~
      ignore_index: 255