model:
  task: segmentation
  checkpoint: ./weights/resnet/resnet50.pth
  freeze_backbone: False
  architecture:
    full:
      type: ~ # auto
    backbone:
      type: resnet50
    head:
      type: all_mlp_decoder
  losses:
    - criterion: cross_entropy
      weight: ~
      ignore_index: 255