model:
  task: segmentation
  name: resnet50
  checkpoint: ./weights/resnet/resnet50.pth
  fx_model_checkpoint: ~
  resume_optimizer_checkpoint: ~
  freeze_backbone: False
  architecture:
    full:
      name: ~ # auto
    backbone:
      name: resnet
      params:
        block: bottleneck
        norm_layer: batch_norm
        groups: 1
        width_per_group: 64
        zero_init_residual: False
        expansion: ~
      stage_params:
        - 
          plane: 64
          layers: 3
        - 
          plane: 128
          layers: 4
          replace_stride_with_dilation: False
        - 
          plane: 256
          layers: 6
          replace_stride_with_dilation: False
        - 
          plane: 512
          layers: 3
          replace_stride_with_dilation: False
    head:
      name: all_mlp_decoder
      params:
        decoder_hidden_size: 256
        classifier_dropout_prob: 0.
  losses:
    - criterion: cross_entropy
      weight: ~
      ignore_index: 255