model:
  task: detection
  name: resnet50
  checkpoint: ./weights/resnet/resnet50.safetensors
  fx_model_checkpoint: ~
  resume_optimizer_checkpoint: ~
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone:
      name: resnet
      params:
        block: bottleneck
        norm_layer: batch_norm
        groups: 1
        width_per_group: 64
        zero_init_residual: False
        expansion: ~
      stage_params:
        - 
          plane: 64
          layers: 3
        - 
          plane: 128
          layers: 4
          replace_stride_with_dilation: False
        - 
          plane: 256
          layers: 6
          replace_stride_with_dilation: False
        - 
          plane: 512
          layers: 3
          replace_stride_with_dilation: False
    neck:
      name: fpn
      params:
        num_outs: 4
        start_level: 0
        end_level: -1
        add_extra_convs: False
        relu_before_extra_convs: False
        no_norm_on_lateral: False
    head:
      name: retinanet_head
      params:
        anchor_sizes: [[64,], [128,], [256,], [512,]]
        aspect_ratios: [0.5, 1.0, 2.0]
        num_anchors: 3
        norm_layer: batch_norm
        # postprocessor - decode
        topk_candidates: 1000
        score_thresh: 0.05
        # postprocessor - nms
        nms_thresh: 0.45
        class_agnostic: False
  losses:
    - criterion: retinanet_loss
      weight: ~