model:
  task: segmentation
  checkpoint: ./weights/resnet/resnet50.pth
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone: resnet50
    head: all_mlp_decoder
  losses:
    - criterion: cross_entropy
      weight: ~
      ignore_index: 255