model:
  task: segmentation
  name: resnet50
  checkpoint: ./weights/resnet/resnet50.safetensors
  load_checkpoint_head: False
  fx_model_checkpoint: ~
  resume_optimizer_checkpoint: ~
  freeze_backbone: False
  architecture:
    full:
      name: ~ # auto
    backbone:
      name: resnet
      params:
        block_type: bottleneck
        norm_type: batch_norm
      stage_params:
        - 
          channels: 64
          num_blocks: 3
        - 
          channels: 128
          num_blocks: 4
          replace_stride_with_dilation: False
        - 
          channels: 256
          num_blocks: 6
          replace_stride_with_dilation: False
        - 
          channels: 512
          num_blocks: 3
          replace_stride_with_dilation: False
    head:
      name: all_mlp_decoder
      params:
        intermediate_channels: 256
        classifier_dropout_prob: 0.
  losses:
    - criterion: cross_entropy
      weight: ~
      ignore_index: 255