# This issue template is modified from https://github.com/gradio-app/gradio/blob/main/.github/ISSUE_TEMPLATE/bug_report_template.yml
name: "\U0001F41E Bug report"
description: Create a report to help us improve
title: "[BUG] Please write your own title"
labels: ["bug"]
assignees: ""
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Before you get started, please search if an issue already exists for the bug you encountered
  - type: checkboxes
    attributes:
      label: Have you searched existing issues?  🔎
      options:
        - label: I have searched and found no existing issues.
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Please provide a concise description.
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a minimal example, with code, that can be run to reproduce the issue. Do NOT provide screenshots of code, or link to external repos or applications. Use ``` to format code blocks.
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: If relevant, please include screenshot(s) so that we can understand what the issue is.
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please include the full stacktrace of the errors you get from the code.
      render: shell
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Please ensure that you use the latest version of this package. If you use the customized version of this package, you may fill out the system information in more details.
      render: shell
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Will you help us by submitting a PR?
      options:
        - label: I will submit a PR about this issue.
  - type: markdown
    attributes:
      value: |
        📌  Please ensure that you have filled all of the required sections above, and that the reproduction you have provided is [minimal, complete, and reproducible](https://stackoverflow.com/help/minimal-reproducible-example). Incomplete issues will be closed.