logging:
  project_id: ~
  output_dir: ./outputs
  tensorboard: true
  image: true
  stdout: true
  save_optimizer_state: true
  save_best_only: false
  sample_input_size: [640, 640] # Used for flops and onnx export
  onnx_export_opset: 13 # Recommend in range [13, 17]
  validation_epoch: &validation_epoch 10
  save_checkpoint_epoch: *validation_epoch  # Multiplier of `validation_epoch`.