model:
  task: classification
  name: mobilenet_v4_conv_large
  checkpoint:
    use_pretrained: True
    load_head: False
    path: ~
    fx_model_path: ~
    optimizer_path: ~
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone:
      name: mobilenetv4
      params:
        stem_out_channel: 24
        stem_kernel_size: 3
        stem_stride: 2
        final_conv_out_channel: 960
        final_conv_kernel_size: 1
        final_conv_stride: 1
        norm_type: batch_norm
        act_type: relu
        return_stage_idx: ~
      stage_params:
        - 
          block_type: fused_inverted
          in_channels: [24]
          hidden_channels: [96]
          out_channels: [48]
          kernel_size: [3]
          stride: [2]
          out_act: [False]
        - 
          block_type: universal_inverted_residual
          in_channels: [48, 96]
          hidden_channels: [192, 384]
          out_channels: [96, 96]
          extra_dw: [True, True]
          extra_dw_kernel_size: [3, 3]
          middle_dw: [True, True]
          middle_dw_kernel_size: [5, 3]
          stride: [2, 1]
        - 
          block_type: universal_inverted_residual
          in_channels: [96, 192, 192, 192, 192, 192, 192, 192, 192, 192, 192]
          hidden_channels: [384, 768, 768, 768, 768, 768, 768, 768, 768, 768, 768]
          out_channels: [192, 192, 192, 192, 192, 192, 192, 192, 192, 192, 192]
          extra_dw: [True, True, True, True, True, True, True, True, True, True, True]
          extra_dw_kernel_size: [3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 3]
          middle_dw: [True, True, True, True, True, True, True, True, True, True, False]
          middle_dw_kernel_size: [5, 3, 3, 3, 5, 3, 3, 3, 3, 3, ~]
          stride: [2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
        - 
          block_type: universal_inverted_residual
          in_channels: [192, 512, 512, 512, 512, 512, 512, 512, 512, 512, 512, 512, 512]
          hidden_channels: [768, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048]
          out_channels: [512, 512, 512, 512, 512, 512, 512, 512, 512, 512, 512, 512, 512]
          extra_dw: [True, True, True, True, True, True, True, True, True, True, True, True, True]
          extra_dw_kernel_size: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
          middle_dw: [True, True, True, True, False, True, False, False, True, True, False, False, False]
          middle_dw_kernel_size: [5, 5, 5, 5, ~, 3, ~, ~, 3, 5, ~, ~, ~]
          stride: [2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    head:
      name: fc_conv
      params:
        num_layers: 2
        intermediate_channels: 1280
        act_type: relu
        norm_type: batch_norm
        dropout_prob: 0.
  postprocessor: ~
  losses:
    - criterion: cross_entropy
      label_smoothing: 0.1
      weight: ~