model:
  task: classification
  name: mobilenet_v4_conv_large
  checkpoint:
    use_pretrained: True
    load_head: True
    path: ~
    fx_model_path: ~
    optimizer_path: ~
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone:
      name: mobilenetv4
      params:
        stem_out_channel: 24
        stem_kernel_size: 3
        stem_stride: 2
        final_conv_out_channel: 960
        final_conv_kernel_size: 1
        final_conv_stride: 1
        norm_type: batch_norm
        act_type: relu
        return_stage_idx: ~
      stage_params:
        # Conv2D: ['conv', out_channels, kernel_size, stride]
        # FusedIB: ['fi', out_channels, hidden_channels, kernel_size, stride]
        # UniversalInvertedResidualBlock: ['uir', out_channels, hidden_channels, extra_dw, extra_dw_kernel_size, middle_dw, middle_dw_kernel_size, stride]
        # MobileMultiQueryAttention2D: ['mmqa', out_channels, attention_channel, num_attention_heads, query_pooling_stride, key_val_downsample, key_val_downsample_kernel_size, key_val_downsample_stride, stride]
        - 
          - ['fi', 48, 96, 3, 2]
        - 
          - ['uir', 96, 192, True, 3, True, 5, 2]
          - ['uir', 96, 384, True, 3, True, 3, 1]
        - 
          - ['uir', 192, 384, True, 3, True, 5, 2]
          - ['uir', 192, 768, True, 3, True, 3, 1]
          - ['uir', 192, 768, True, 3, True, 3, 1]
          - ['uir', 192, 768, True, 3, True, 3, 1]
          - ['uir', 192, 768, True, 3, True, 5, 1]
          - ['uir', 192, 768, True, 5, True, 3, 1]
          - ['uir', 192, 768, True, 5, True, 3, 1]
          - ['uir', 192, 768, True, 5, True, 3, 1]
          - ['uir', 192, 768, True, 5, True, 3, 1]
          - ['uir', 192, 768, True, 5, True, 3, 1]
          - ['uir', 192, 768, True, 3, False, ~, 1]
        - 
          - ['uir', 512, 768, True, 5, True, 5, 2]
          - ['uir', 512, 2048, True, 5, True, 5, 1]
          - ['uir', 512, 2048, True, 5, True, 5, 1]
          - ['uir', 512, 2048, True, 5, True, 5, 1]
          - ['uir', 512, 2048, True, 5, False, ~, 1]
          - ['uir', 512, 2048, True, 5, True, 3, 1]
          - ['uir', 512, 2048, True, 5, False, ~, 1]
          - ['uir', 512, 2048, True, 5, False, ~, 1]
          - ['uir', 512, 2048, True, 5, True, 3, 1]
          - ['uir', 512, 2048, True, 5, True, 5, 1]
          - ['uir', 512, 2048, True, 5, False, ~, 1]
          - ['uir', 512, 2048, True, 5, False, ~, 1]
          - ['uir', 512, 2048, True, 5, False, ~, 1]
    head:
      name: fc_conv
      params:
        num_layers: 2
        intermediate_channels: 1280
        act_type: relu
        norm_type: batch_norm
        dropout_prob: 0.
  postprocessor: ~
  losses:
    - criterion: cross_entropy
      label_smoothing: 0.1
      weight: ~