training:
  seed: 1
  opt: adamw
  lr: 6e-5
  momentum: 0.937
  weight_decay: 0.0005
  sched: cosine
  min_lr: 1e-6
  warmup_bias_lr: 1e-5
  warmup_epochs: 5
  iters_per_phase: 30
  sched_power: 1.0
  epochs: 3
  batch_size: 32 
