training:
  seed: 1
  sched: cosine
  min_lr: 1e-6
  warmup_bias_lr: 1e-5
  warmup_epochs: 5
  iters_per_phase: 30
  sched_power: 1.0
  epochs: 3
  batch_size: 32 
  optimizer:
    name: adamw
    lr: 6e-5
    betas: [0.9, 0.999]
    weight_decay: 0.0005
