training:
  seed: 1
  opt: adamw
  lr0: 0.0001
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_steps: 100 
  warmup_epochs: 5
  warmup_momentum: 0.8
  warmup_bias_lr: ~
  schd_power: 1.0
  epochs: 3
  batch_size: 32 
  freeze: ~ 