model:
  task: segmentation
  checkpoint: ./weights/segformer/segformer.pth
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone: segformer
    head: all_mlp_decoder
  losses:
    - criterion: cross_entropy
      weight: ~
      ignore_index: 255