model:
  task: segmentation
  checkpoint: ./weights/segformer/segformer.pth
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone:
      name: segformer
    head:
      name: all_mlp_decoder
  losses:
    - criterion: cross_entropy
      weight: ~
      ignore_index: 255