model:
  task: segmentation
  checkpoint: ./weights/segformer/segformer.pth
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone:
      name: segformer
    head:
      name: fc
  losses:
    - criterion: label_smoothing_cross_entropy
      smoothing: 0.1
      weight: ~