datasets:
  task: classification
  path:
    root: ./data/classification # dataset root
    train:
      image: train # directory for training images
    valid:
      image: val  # directory for valid images
  id_mapping: ~