model:
  task: segmentation
  name: mobilenet_v3_small
  checkpoint:
    use_pretrained: True
    load_head: False
    path: ~
    fx_model_path: ~
    optimizer_path: ~
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone:
      name: mobilenetv3
      params: ~
      stage_params:
        -
          in_channels: [16]
          kernel_sizes: [3]
          expanded_channels: [16]
          out_channels: [16]
          use_se: [True]
          act_type: ["relu"]
          stride: [2]
        -
          in_channels: [16, 24]
          kernel_sizes: [3, 3]
          expanded_channels: [72, 88]
          out_channels: [24, 24]
          use_se: [False, False]
          act_type: ["relu", "relu"]
          stride: [2, 1]
        -
          in_channels: [24, 40, 40, 40, 48]
          kernel_sizes: [5, 5, 5, 5, 5]
          expanded_channels: [96, 240, 240, 120, 144]
          out_channels: [40, 40, 40, 48, 48]
          use_se: [True, True, True, True, True]
          act_type: ["hard_swish", "hard_swish", "hard_swish", "hard_swish", "hard_swish"]
          stride: [2, 1, 1, 1, 1]
        -
          in_channels: [48, 96, 96]
          kernel_sizes: [5, 5, 5]
          expanded_channels: [288, 576, 576]
          out_channels: [96, 96, 96]
          use_se: [True, True, True]
          act_type: ["hard_swish", "hard_swish", "hard_swish"]
          stride: [2, 1, 1]
    head:
      name: all_mlp_decoder
      params:
        intermediate_channels: 256
        classifier_dropout_prob: 0.
  postprocessor: ~
  losses:
    - criterion: seg_cross_entropy
      weight: ~
      ignore_index: 255 # Default undefined class is 255