model:
  task: detection
  name: mobilenet_v3_small
  checkpoint:
    use_pretrained: True
    load_head: False
    path: ~
    fx_model_path: ~
    optimizer_path: ~
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone:
      name: mobilenetv3
      params: ~
      stage_params:
        -
          in_channels: [16]
          kernel_sizes: [3]
          expanded_channels: [16]
          out_channels: [16]
          use_se: [True]
          act_type: ["relu"]
          stride: [2]
        -
          in_channels: [16, 24]
          kernel_sizes: [3, 3]
          expanded_channels: [72, 88]
          out_channels: [24, 24]
          use_se: [False, False]
          act_type: ["relu", "relu"]
          stride: [2, 1]
        -
          in_channels: [24, 40, 40, 40, 48]
          kernel_sizes: [5, 5, 5, 5, 5]
          expanded_channels: [96, 240, 240, 120, 144]
          out_channels: [40, 40, 40, 48, 48]
          use_se: [True, True, True, True, True]
          act_type: ["hard_swish", "hard_swish", "hard_swish", "hard_swish", "hard_swish"]
          stride: [2, 1, 1, 1, 1]
        -
          in_channels: [48, 96, 96]
          kernel_sizes: [5, 5, 5]
          expanded_channels: [288, 576, 576]
          out_channels: [96, 96, 96]
          use_se: [True, True, True]
          act_type: ["hard_swish", "hard_swish", "hard_swish"]
          stride: [2, 1, 1]
    neck:
      name: fpn
      params:
        num_outs: 4
        start_level: 0
        end_level: -1
        add_extra_convs: False
        relu_before_extra_convs: False
    head:
      name: anchor_decoupled_head
      params:
        anchor_sizes: [[32,], [64,], [128,], [256,]]
        aspect_ratios: [0.5, 1.0, 2.0]
        num_layers: 1
        norm_type: batch_norm
  postprocessor:
    topk_candidates: 1000
    score_thresh: 0.05  # decode
    nms_thresh: 0.45  # nms
    class_agnostic: False
  losses:
    - criterion: retinanet_loss
      weight: ~