logging:
  project_id: ~
  output_dir: ./outputs
  tensorboard: true
  csv: false
  image: true
  stdout: true
  validation_epoch: &validation_epoch 10
  save_checkpoint_epoch: *validation_epoch  # Multiplier of `validation_epoch`.