augmentation:
  img_size: &img_size 256
  transforms:
    - 
      name: randomresizedcrop
      size: *img_size
      interpolation: bilinear
    - 
      name: randomhorizontalflip
      p: 0.5
  mix_transforms:
    -
      name: cutmix
      alpha: 1.0
