augmentation:
  train:
    - 
      name: randomresizedcrop
      size: 256
      scale: [0.08, 1.0]
      ratio: [0.75, 1.33]
      interpolation: bilinear
    - 
      name: randomhorizontalflip
      p: 0.5
    -
      name: mixing
      mixup: [0.25, 1.0]
      cutmix: ~
      inplace: false
  inference:
    - 
      name: resize
      size: [256, 256]
      interpolation: bilinear
      max_size: ~
      resize_criteria: ~
