augmentation:
  train:
    - 
      name: resize
      size: [640, 640]
      interpolation: bilinear
      max_size: ~
      resize_criteria: ~
    -
      name: totensor
      pixel_range: 1.0
    -
      name: normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  inference:
    - 
      name: resize
      size: [640, 640]
      interpolation: bilinear
      max_size: ~
      resize_criteria: ~
    -
      name: totensor
      pixel_range: 1.0
    -
      name: normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]