augmentation:
  img_size: &img_size 512
  train:
    - 
      name: resize
      size: [*img_size, *img_size]
      interpolation: bilinear
      max_size: ~
  inference:
    - 
      name: resize
      size: [*img_size, *img_size]
      interpolation: bilinear
      max_size: ~
