augmentation:
  train:
    - 
      name: resize
      size: [512, 512]
      interpolation: bilinear
      max_size: ~
      resize_criteria: ~
  inference:
    - 
      name: resize
      size: [512, 512]
      interpolation: bilinear
      max_size: ~
      resize_criteria: ~
