model:
  task: classification
  checkpoint: ./weights/mixnet/mixnet_s.pth
  fx_model_checkpoint: ~
  resume_optimizer_checkpoint: ~
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone:
      name: mixnet
      params:
        stem_planes: 16
        width_multi: 1.0
        depth_multi: 1.0
        dropout_rate: 0.
      stage_params: 
        -
          # t, c,  n, k,                ek,     pk,     s, d,  a,      se
          - [1, 16, 1, [3], [1], [1], 1, 1, "relu", ~]
          - [6, 24, 1, [3], [1, 1], [1, 1], 2, 1, "relu", ~]
          - [3, 24, 1, [3], [1, 1], [1, 1], 1, 1, "relu", ~]
        -
          - [6, 40, 1, [3, 5, 7], [1], [1], 2, 1, "swish", 2]
          - [6, 40, 3, [3, 5], [1, 1], [1, 1], 1, 1, "swish", 2]
        -
          - [6, 80, 1, [3, 5, 7], [1], [1, 1], 2, 1, "swish", 4]
          - [6, 80, 2, [3, 5], [1], [1, 1], 1, 1, "swish", 4]
          - [6, 120, 1, [3, 5, 7], [1, 1], [1, 1], 1, 1, "swish", 2]
          - [3, 120, 2, [3, 5, 7, 9], [1, 1], [1, 1], 1, 1, "swish", 2]
        -
          - [6, 200, 1, [3, 5, 7, 9, 11], [1], [1], 2, 1, "swish", 2]
          - [6, 200, 2, [3, 5, 7, 9], [1], [1, 1], 1, 1, "swish", 2]
    head:
      name: fc
  losses:
    - criterion: cross_entropy
      label_smoothing: 0.1
      weight: ~