model:
  task: segmentation
  name: mixnet_s
  checkpoint: ./weights/mixnet/mixnet_s.pth
  fx_model_checkpoint: ~
  resume_optimizer_checkpoint: ~
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone:
      name: mixnet
      params:
        stem_planes: 16
        width_multi: 1.0
        depth_multi: 1.0
        dropout_rate: 0.
      stage_params: 
        -
          expand_ratio: [1, 6, 3]
          out_channels: [16, 24, 24]
          num_blocks: [1, 1, 1]
          kernel_sizes: [[3], [3], [3]]
          exp_kernel_sizes: [[1], [1, 1], [1, 1]]
          poi_kernel_sizes: [[1], [1, 1], [1, 1]]
          stride: [1, 2, 1]
          dilation: [1, 1, 1]
          act_type: ["relu", "relu", "relu"]
          se_reduction_ratio: [~, ~, ~]
        -
          expand_ratio: [6, 6]
          out_channels: [40, 40]
          num_blocks: [1, 3]
          kernel_sizes: [[3, 5, 7], [3, 5]]
          exp_kernel_sizes: [[1], [1, 1]]
          poi_kernel_sizes: [[1], [1, 1]]
          stride: [2, 1]
          dilation: [1, 1]
          act_type: ["swish", "swish"]
          se_reduction_ratio: [2, 2]
        -
          expand_ratio: [6, 6, 6, 3]
          out_channels: [80, 80, 120, 120]
          num_blocks: [1, 2, 1, 2]
          kernel_sizes: [[3, 5, 7], [3, 5], [3, 5, 7], [3, 5, 7, 9]]
          exp_kernel_sizes: [[1], [1], [1, 1], [1, 1]]
          poi_kernel_sizes: [[1, 1], [1, 1], [1, 1], [1, 1]]
          stride: [2, 1, 1, 1]
          dilation: [1, 1, 1, 1]
          act_type: ["swish", "swish", "swish", "swish"]
          se_reduction_ratio: [4, 4, 2, 2]
        -
          expand_ratio: [6, 6]
          out_channels: [200, 200]
          num_blocks: [1, 2]
          kernel_sizes: [[3, 5, 7, 9, 11], [3, 5, 7, 9]]
          exp_kernel_sizes: [[1], [1]]
          poi_kernel_sizes: [[1], [1, 1]]
          stride: [2, 1]
          dilation: [1, 1]
          act_type: ["swish", "swish"]
          se_reduction_ratio: [2, 2]
    head:
      name: all_mlp_decoder
      params:
        decoder_hidden_size: 256
        classifier_dropout_prob: 0.
  losses:
    - criterion: cross_entropy
      weight: ~
      ignore_index: 255