model:
  task: detection
  name: yolo_fastest
  checkpoint:
    use_pretrained: False
    load_head: False
    path: ~
    fx_model_path: ~
    optimizer_path: ~
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone:
      name: darknet
      params: 
        # stage_stem_block_type: Bottleneck 
        stage_stem_block_type: darknetblock
        depthwise: True
        norm_type: batch_norm
        act_type: relu6
        num_feat_layers: 2
        stem_stride: 2
        stem_out_channels: 8
      stage_params:
        - # stage_1
          out_channels: 4
          num_blocks: 1                     # not the stage stem block  
          darknet_expansions: [2, 2]
        - # stage_2
          out_channels: 8
          num_blocks: 2
          darknet_expansions: [3, 4]
        - # stage_3
          out_channels: 8
          num_blocks: 2
          darknet_expansions: [4, 6]
        - # stage_4
          out_channels: 16
          num_blocks: 4
          darknet_expansions: [3, 6]
        - # stage_5
          out_channels: 24
          num_blocks: 4
          darknet_expansions: [4, 5.67]      # expands to 136 channels 
        - # stage_6
          out_channels: 48
          num_blocks: 5
          darknet_expansions: [2.84, 4.67]   # expands to 224 channels
    neck: 
      name: yolov3fpn
      params:
        out_channels: [48, 24]
        kernel_size: 5
        double_channel: False
        share_fpn_block: False
        depthwise: True
        norm_type: batch_norm
        act_type: leaky_relu
    head:
      name: yolo_fastest_head
      params:
        anchors:
          - [12.64,19.39, 37.88,51.48, 55.71,138.31]  # P4/16
          - [126.91,78.23, 131.57,214.55, 279.92,258.87]  # P5/32]
        # strides: [16, 32]
        norm_type: batch_norm
        topk_candidates: 1000
        # postprocessor - decode
        score_thresh: 0.0
        # postprocessor - nms
        nms_thresh: 0.45
        class_agnostic: False
 # Temporary loss to test the full YOLOFastest model to work right
  losses:
    - criterion: retinanet_loss
      weight: ~
