model:
  task: detection
  name: yolofastest
  checkpoint:
    use_pretrained: False
    load_head: False
    path: ~ 
    fx_model_path: ~
    optimizer_path: ~
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone:
      name: shufflenetv2
      params: ~ 
      stage_params: 
        out_channels: [-1, 24, 48, 96, 192]
    neck:
      name: lightfpn
      params:
        out_depth: 72
    head:
      name: yolo-fastest-head 
      params:
        anchor_num: 3
  losses:
    - criterion: yolofastest_loss
      weight: ~
      l1_activate_epoch: 1
