training:
  epochs: 90
  mixed_precision: False
  ema: ~
  max_norm: ~
  optimizer:
    name: sgd
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0001
    nesterov: False
    no_bias_decay: False
    no_norm_weight_decay: False
    overwrite: ~
  scheduler:
    name: step
    iters_per_phase: 30
    gamma: 0.1
    end_epoch: 90
