model:
  task: detection
  name: yolox_s
  checkpoint:
    use_pretrained: True
    load_head: False
    path: ~ 
    fx_model_path: ~
    optimizer_path: ~
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone:
      name: cspdarknet
      params:
        depthwise: False
        dep_mul: &dep_mul 0.33
        wid_mul: 0.5
        act_type: &act_type "silu"
      stage_params: ~
    neck:
      name: rtdetr_hybrid_encoder
      params:
        hidden_dim: 256
        use_encoder_idx: [2]
        num_encoder_layers: 1
        pe_temperature: 10000
        num_attention_heads: 8
        dim_feedforward: 1024
        dropout: 0.0
        attn_act_type: gelu
        expansion: 0.5
        depth_mult: 1.0
        conv_act_type: silu
    head:
      name: rtdetr_head
      params:
        hidden_dim: 256
        num_attention_heads: 8
        num_levels: 3
        num_queries: 300
        eps: 1e-2
        num_decoder_layers: 3
        eval_spatial_size: ~
        position_embed_type: sine
        num_decoder_points: 4
        dim_feedforward: 1024
        dropout: 0.0
        act_type: relu
        num_denoising: 100
        label_noise_ratio: 0.5
  postprocessor: ~
  losses:
    - criterion: yolox_loss
      weight: ~
      l1_activate_epoch: 1