model:
  task: detection
  name: rtdetr_res18
  checkpoint:
    use_pretrained: True
    load_head: False
    path: ~
    optimizer_path: ~
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone:
      name: resnet
      params:
        block_type: basicblock
        norm_type: batch_norm
        return_stage_idx: [1, 2, 3]
        split_stem_conv: True
        first_stage_shortcut_conv: True
      stage_params:
        - 
          channels: 64
          num_blocks: 2
        - 
          channels: 128
          num_blocks: 2
          replace_stride_with_dilation: False
          replace_stride_with_pooling: True
        - 
          channels: 256
          num_blocks: 2
          replace_stride_with_dilation: False
          replace_stride_with_pooling: True
        - 
          channels: 512
          num_blocks: 2
          replace_stride_with_dilation: False
          replace_stride_with_pooling: True
    neck:
      name: rtdetr_hybrid_encoder
      params:
        hidden_dim: 256
        use_encoder_idx: [2]
        num_encoder_layers: 1
        pe_temperature: 10000
        num_attention_heads: 8
        dim_feedforward: 1024
        dropout: 0.0
        attn_act_type: gelu
        expansion: 0.5
        depth_mult: 1.0
        conv_act_type: silu
    head:
      name: rtdetr_head
      params:
        hidden_dim: 256
        num_attention_heads: 8
        num_levels: 3
        num_queries: 300
        eps: 1e-2
        num_decoder_layers: 3
        eval_spatial_size: ~
        position_embed_type: sine
        num_decoder_points: 4
        dim_feedforward: 1024
        dropout: 0.0
        act_type: relu
        num_denoising: 100
        label_noise_ratio: 0.5
        use_aux_loss: true
  postprocessor:
    params:
      num_top_queries: 300
      score_thresh: 0.0
  losses:
    - criterion: detr_loss
      weight: ~
      weight_dict: {loss_vfl: 1, loss_bbox: 5, loss_giou: 2,}
      losses: ['vfl', 'boxes']
      alpha: 0.75
      gamma: 2.0
      matcher:
        type: HungarianMatcher
        weight_dict: {cost_class: 2, cost_bbox: 5, cost_giou: 2}
        # use_focal_loss: True
        alpha: 0.25
        gamma: 2.0
        use_focal_loss: true
