model:
  task: classification
  checkpoint: ./weights/mobilevit/mobilevit_s.pth
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone: mobilevit
    head: fc
  losses:
    - criterion: label_smoothing_cross_entropy
      smoothing: 0.1
      weight: ~