model:
  task: classification
  checkpoint: ./weights/mobilevit/mobilevit_s.pth
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone:
      name: mobilevit
    head:
      name: fc
  losses:
    - criterion: label_smoothing_cross_entropy
      smoothing: 0.1
      weight: ~