model:
  task: classification
  name: mobilevit_s
  checkpoint:
    use_pretrained: True
    load_head: False
    path: ~
    fx_model_path: ~
    optimizer_path: ~
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone:
      name: mobilevit
      params:
        patch_size: 2
        num_attention_heads: 4  # num_heads
        attention_dropout_prob: 0.1
        ffn_dropout_prob: 0.0
        output_expansion_ratio: 4
        use_fusion_layer: True
      stage_params:
        -
          block_type: 'mv2'
          out_channels: 32
          num_blocks: 1
          stride: 1
          ir_expansion_ratio: 4  # [mv2_exp_mult] * 4
        -
          block_type: 'mv2'
          out_channels: 64
          num_blocks: 3
          stride: 2
          ir_expansion_ratio: 4  # [mv2_exp_mult] * 4
        -
          block_type: 'mobilevit'
          out_channels: 96
          num_blocks: 2
          stride: 2
          attention_channels: 144
          ffn_intermediate_channels: 288
          dilate: False
          ir_expansion_ratio: 4  # [mv2_exp_mult] * 4
        -
          block_type: 'mobilevit'
          out_channels: 128
          num_blocks: 4
          stride: 2
          attention_channels: 192
          ffn_intermediate_channels: 384
          dilate: False
          ir_expansion_ratio: 4  # [mv2_exp_mult] * 4
        -
          block_type: 'mobilevit'
          out_channels: 160
          num_blocks: 3
          stride: 2
          attention_channels: 240
          ffn_intermediate_channels: 480
          dilate: False
          ir_expansion_ratio: 4  # [mv2_exp_mult] * 4
    head:
      name: fc
      params:
        num_layers: 1
        intermediate_channels: ~
        act_type: ~
        dropout_prob: 0.
  postprocessor: ~
  losses:
    - criterion: cross_entropy
      label_smoothing: 0.1
      weight: ~