# This workflow is originated from https://github.com/gradio-app/gradio/blob/main/.github/workflows/check-changelog.yml
name: check-changelog

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  check-changelog-updated:
    name: Check CHANGELOG file
    runs-on: ubuntu-latest
    if: ${{ !contains( github.event.pull_request.labels.*.name, 'no-changelog-update') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Release notes added
        run: |
          cat CHANGELOG.md | grep -w "https://github.com/nota-netspresso/netspresso-trainer/pull/${{ github.event.number }}"