name: Deploy documentation

on:
  push:
    tags:
     - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install mkdocs
      run: |
        python -m pip install mkdocs
    - name: Install mkdocs-material
      run: |
        python -m pip install mkdocs-material
    - name: Publish docs
      run: |
        mkdocs gh-deploy --force